### ISSUE TITLE
Tenet: do-not-discard-errors. Need to check if there is a comment explaining discarding

### ISSUE THREAD

**Issue by Daanikus** [codelingo/codelingo#242]
Waiting on SRC lexicon for querying line numbers

**Comment by mullikine** [comment]
https://trello.com/c/ijtJKRHI/1925-src-lexicon

**Comment by BlakeMScurr** [comment]
@Daanikus shouldn't the comment sit directly adjacent to the error assignment? Also, why have this check? Let people edit the tenet themselves if they want to, we want full visibility on the all discarded errors.

**Comment by Daanikus** [comment]
@BlakeMScurr Good point. I think the comment explaining a discarded error shouldn't excuse it. I'm sure I read that in EG but maybe not. We can probably close this issue if we're not allowing comments as an excuse. The querying of line numbers was needed to determine if a comment was referring to the discarded error as they are not attached to facts (except func comments)

**Comment by BlakeMScurr** [comment]
OK cool, let's close this. Your SRC lexicon point stands, the Go parser should really handle that. I think a comment should be attached to the following AST node.

**Comment by BlakeMScurr** [comment]
To clarify, I closed this because discarding errors is a bad practice and our tenet should be strict on it by default. The relevant effective go [paragraph](https://golang.org/doc/effective_go.html#blank_assign) does not mention exceptions for comments.

If a user really wants exceptions they can edit it in their own codelingo.yaml file.
